download:
  podcasts_path: /home/nikita/balalaika 
  episodes_limit: 1 # limit on downloading episodes from one playlist
  num_workers: 1
  podcasts_urls_file: '/home/nikita/yapoddataset/20000_more_albums.pkl' # pkl with urls
  
preprocess:
  podcasts_path: /home/nikita/balalaika # full path to the folder where the podcasts are located 
  duration: 15 # in seconds (each sample will be no longer than this time.)
  num_workers: 1
  smart_vad_model: pipecat-ai/smart-turn-v2
  

separation:
  podcasts_path: /home/nikita/balalaika # full path to the folder where the chopped podcasts are located 
  num_workers: 1
  nisqa_config: "configs/nisqa_s.yaml"
  one_speaker: False # When this option is enabled, only single-speaker audio recordings are downloaded.

transcription:
  podcasts_path: /home/nikita/balalaika # full path to the folder where the chopped podcasts are located 
  num_workers: 1 # per one gpu
  model_names: ['vosk', 'tone', 'giga_rnnt', 'giga_ctc', 'giga_ctc_lm']
  vosk_path: /home/nikita/yapoddataset/models/vosk-model-ru
  lm_path: '/home/nikita/yapoddataset/kenlm.bin' # path to lm.bin
  with_timestamps: True
  
punctuation:
  podcasts_path: /home/nikita/balalaika # full path to the folder where the chopped podcasts are located 
  model_name: "RUPunct/RUPunct_big" # RUPunct model name 
  num_workers: 4 # per one gpu

accent:
  podcasts_path: /home/nikita/balalaika # full path to the folder where the chopped podcasts are located 
  num_workers: 4 # per one gpu
  model_name: turbo3.1 # ruAccent model name 
  
phonemizer:
  podcasts_path: /home/nikita/balalaika # full path to the folder where the text files are located
  num_workers: 4 # per one gpu

classification:
  podcasts_path: /home/nikita/balalaika
  num_workers: 4 # per one gpu
  threshold: 0.6
  model_path: models/voxblink2_samresnet100_ft # .pt format model from https://github.com/wenet-e2e/wespeaker/blob/master/docs/pretrained.md


  
